### ISSUE TITLE
Test that type hints are used for model selection

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#136]
#135 adds type hints to the model, but they are not tested for the model-building part. Mocking can help, maybe using ``CheckingClassifier``?

**Comment by satishjasthi** [comment]
Hi Amueller, I'm trying to understand this issue please correct me if Im wrong
 Through #135 you have added type hints in _fit method which detect types of dataframe columns, and I see that test case has been created for the function detect_types in test_preprocessing.py.
I wasn't able to understand "but they are not tested for the model-building part". Can you please elaborate.
Thank you

**Comment by amueller** [comment]
Hi @satishjasthi. Thanks for your interest. I think you're right, the testing seems appropriate. What I originally envisioned was testing that the right columns are passed to the classifier but maybe that's not necessary if we know that the column transformer does the right thing. Thanks for looking into it!
