### ISSUE TITLE
really long column names mess up plots

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#148]
we should ensure axes labels are shortened

**Comment by IanCarrasco** [comment]
Is this already taken care of by 
```
_shortname 
```
in plot/utils.py?

**Comment by amueller** [comment]
There is a _shortname function but it's not currently applied to axes labels.

**Comment by kumanday** [comment]
https://github.com/amueller/dabl/pull/180

Before and after images:

**Classes**
Before:
<img width="1209" alt="classes-before" src="https://user-images.githubusercontent.com/1234749/73457220-566ada80-4341-11ea-97d8-f7fda9c07ec7.png">

After:
<img width="1204" alt="classes-after" src="https://user-images.githubusercontent.com/1234749/73457224-566ada80-4341-11ea-8b6e-d24be26f25d5.png">

**Coefficients**
Before:
<img width="889" alt="coefficients-before" src="https://user-images.githubusercontent.com/1234749/73457225-566ada80-4341-11ea-8316-2322555c83c4.png">

After:
<img width="873" alt="coefficients-after" src="https://user-images.githubusercontent.com/1234749/73457221-566ada80-4341-11ea-8301-67fb3b75b269.png">

**Interactions**
Before:
<img width="1185" alt="interactions-before" src="https://user-images.githubusercontent.com/1234749/73457227-57037100-4341-11ea-9d79-f58257e075ba.png">

After:
<img width="1184" alt="interactions-after" src="https://user-images.githubusercontent.com/1234749/73457223-566ada80-4341-11ea-991e-2a5473ab2173.png">
