### ISSUE TITLE
add example for mosaic_plot

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#167]
Add example for a stand-alone call to mosaic_plot, and maybe add an example to the docstring as well.

**Comment by satishjasthi** [comment]
Hi amueller, just wanted to clarify where should I added the example for mosaic_plot?
I think for docs, it should be added to user_guide.rst in docs folder right?

**Comment by amueller** [comment]
Thanks for your interest. It should be added inline as an "Example" section, and as a stand-alone file to the ``examples`` subfolder. Check out #169 for an example.
