### ISSUE TITLE
Move to own organization

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#168]
dabl should move to its own org.
@dabl you don't seem very active. Would you mind giving up your user name so we could use it as an organization name?
Alternatively we could use the dabl-dev org, but that makes for uglier URLs for the github pages.

**Comment by dabl34** [comment]
Yes I can do this.


Le mar. 28 janv. 2020 à 20:22, Andreas Mueller <notifications@github.com> a
écrit :

**Comment by amueller** [comment]
Awesome, thank you! merci beaucoup!

**Comment by amueller** [comment]
I think it would just involve you changing your name to anything else.

**Comment by dabl34** [comment]
You're welcome. I'll change my user name within the next 10 minutes, you ready to take it ?

**Comment by amueller** [comment]
yes, thanks! I don't think anyone is gonna snatch it, though :)

**Comment by amueller** [comment]
Thanks, got it! yay!
