### ISSUE TITLE
Minor language change suggestion

### ISSUE THREAD

**Issue by ianozsvald** [dabl/dabl#177]
`"Need to specify exactly one of y and target_col."` at https://github.com/amueller/dabl/blob/master/dabl/plot/supervised.py#L522 might be easier to understand with "or", e.g. `"Need to specify exactly one of y _or_ target_col."`. I misread it the first time I called `plot()` and provided both. This would then match the function signature.

**Comment by amueller** [comment]
Thanks. I find it hard to say xor in English ;) 'or' seems better here. Do you want to send a PR? The phrase is used in several places I think.

**Comment by ianozsvald** [comment]
@parthpankajtiwary thanks for fixing :-)

**Comment by amueller** [comment]
Fixed in #198.
