### ISSUE TITLE
Suggestion - link to pandas_profiling in README

### ISSUE THREAD

**Issue by ianozsvald** [dabl/dabl#178]
The Pandas Profiling package is great for initial univariate analysis (distributions, missing data, outliers) and for generating a data report. I teach it alongside dabl, maybe link to it from the README as it is complimentary?

https://github.com/pandas-profiling/pandas-profiling

**Comment by amueller** [comment]
Good idea. Wanna send a PR?

**Comment by ianozsvald** [comment]
Will do these in the next day or so, cheers

**Comment by amueller** [comment]
Thanks :) Also happy to leave your other suggestions open for new contributors though!

**Comment by ianozsvald** [comment]
I'm talking to my students in the morning, I'm going to suggest one of them take this up as their first open source contribution, let's see what they say

**Comment by amueller** [comment]
Perfect!

**Comment by amueller** [comment]
Fixed in #213.
