### ISSUE TITLE
Cannot import dabl

### ISSUE THREAD

**Issue by suvayu** [dabl/dabl#18]
I installed `dabl` like this:

    $ cd /path/to/dabl-repo
    $ pip3 install --user -e .

But when I import from `ipython`, it fails with:

    In [ ]: import dabl
    ImportError                               Traceback (most recent call last)
    <ipython-input-4-6b072d28c65f> in <module>
    ----> 1 import dabl

    ~/build/data-an/dabl/dabl/__init__.py in <module>
          2 from .models import SimpleClassifier, SimpleRegressor
          3 from .plot.supervised import plot_supervised
    ----> 4 from .explain import explain
          5
          6 __all__ = ['EasyPreprocessor', 'SimpleClassifier', 'SimpleRegressor',

    ~/build/data-an/dabl/dabl/explain.py in <module>
          1 import numpy as np
          2
    ----> 3 from sklearn.tree import DecisionTreeClassifier, plot_tree
          4 from sklearn.ensemble import RandomForestClassifier
          5 from sklearn.pipeline import Pipeline

    ImportError: cannot import name 'plot_tree'

I couldn't find a `plot_tree` function in [`sklearn.tree`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.tree), are you using a development version?

**Comment by NicolasHug** [comment]
Yes `plot_tree` will be part of 0.21 but is only accessible from the master branch of scikit-learn for now

**Comment by suvayu** [comment]
Okay thanks.  Maybe this dependency requirement could be made explicit somewhere, either in `setup.py` or the `README`?

**Comment by NicolasHug** [comment]
Yes we could add a note in the readme, feel free to submit a PR!

**Comment by amueller** [comment]
I think actually we should backport this, I just realized CI is failing because of it.

**Comment by suvayu** [comment]
Ah, that would be even better!  Please reject my PR in that case :)

**Comment by amueller** [comment]
Sorry for the inconvenience, I realized this just this morning, gonna fix it! Thanks though.

**Comment by MertNuhuz** [comment]
Hi, I wonder how long it will take you to fix 🙂. According to him I will install the latest version of sklearn

**Comment by amueller** [comment]
@NicolasHug said he'll do it ;) if not I'll do it in the next hour or so.

**Comment by MertNuhuz** [comment]
Okay, thank you 🙂

**Comment by NicolasHug** [comment]
I'm on it

**Comment by amueller** [comment]
Fixed, thank you @NicolasHug !
