### ISSUE TITLE
website raises 404

### ISSUE THREAD

**Issue by jmschrei** [dabl/dabl#183]
https://amueller.github.io/dabl/ gives me a sad 404 error and now I'll never know what this project is about.

**Comment by thomasjpfan** [comment]
Link is now https://dabl.github.io/dabl

**Comment by NicolasHug** [comment]
The project link visible from https://github.com/dabl/dabl should be updated tho

**Comment by amueller** [comment]
it's back up and everything is updated now. Y'all are to quick! The old one has a redirect (thought no deep redirects).

**Comment by amueller** [comment]
the link is https://dabl.github.io now, dabl.github.io/dabl is gone and existed for all of 20 minutes ;)

**Comment by amueller** [comment]
feel free to reopen if it persists.
