### ISSUE TITLE
Data files are missing in PyPI release

### ISSUE THREAD

**Issue by seljukgulcan** [dabl/dabl#206]
It is the same problem as #126 . It is marked as closed however I think the problem still continues.

I installed dabl with pip and tried to run sample code in quickstart page. 

`titanic = pd.read_csv(dabl.datasets.data_path("titanic.csv"))` This line gives error since related file is not in datasets folder. The error applies for other data files as well.

**Comment by amueller** [comment]
Hi @Shathra. Thanks for reporting. What version of dabl do you have? (``print(dabl.__version__)``)

**Comment by seljukgulcan** [comment]
0.1.7

**Comment by amueller** [comment]
Thanks, I'll look into it!

**Comment by amueller** [comment]
Can you install 0.1.8 and check if it fixed it?

**Comment by seljukgulcan** [comment]
Yes, I checked and it's working now, thanks.

**Comment by amueller** [comment]
Great, thanks for reporting and following up!
