### ISSUE TITLE
drop outliers in regression target for plotting

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#214]
Nice example of the plotting having issues with outliers is
``topo_2_1``

**Comment by vaibhavkumar11** [comment]
Which plot is being referred by `topo_2_1`?

**Comment by amueller** [comment]
sorry for being cryptic, I meant in the ``topo_2_1`` dataset which you can get with ``fetch_mldata('topo_2_1')``. If you plot that with ``plot`` right now you'll see the outliers mess it up and that would be great to fix.

**Comment by vaibhavkumar11** [comment]
Ok, I will try to work on this issue.

**Comment by amueller** [comment]
Great!

**Comment by vaibhavkumar11** [comment]
![Screenshot from 2020-02-23 12-53-36](https://user-images.githubusercontent.com/26917921/75105709-aa18cd00-563c-11ea-9db4-66d36114428a.png)
The plots seem to be fine, so can you please suggest what is messing up?
OS: PopOS 19.10(Kernel : 5.3.0-7625-generic)
Python version: 3.7.6
dabl version: 0.1.8

**Comment by amueller** [comment]
I don't think these plots are very useful, there's I think a single point that really change the limits of the y-axis. If we removed that point, I thin kthe plot would look more useful.

**Comment by amueller** [comment]
Fixed in #233, thanks @SvoONs !
