### ISSUE TITLE
Build fails due to sklearn update

### ISSUE THREAD

**Issue by seljukgulcan** [dabl/dabl#217]
It seems like sklearn updated [`load_digits`](https://scikit-learn.org/dev/modules/generated/sklearn.datasets.load_digits.html) function. Now, the returned object has feature names which breaks `test_digits_type_hints` test in the dev build. It causes PR #216 to fail (will probably fail any future PRs as well)

**Comment by amueller** [comment]
Thanks for reporting. I probably won't have much time for dabl this week but if you want to look into it please go ahead.
