### ISSUE TITLE
Pip version 0.1.8 doesn't contain portfolio option for anyclassifier

### ISSUE THREAD

**Issue by capt-pyro** [dabl/dabl#239]
Dabl pip version 0.1.8 doesn't contain portfolio option for AnyClassifier even though the 0.1.8 docs say its available.

**Comment by amueller** [comment]
Thank you for opening the issue, I'll have a look. It might be a packaging issue.

**Comment by amueller** [comment]
Sorry, I misunderstood, you meant that the ``portfolio`` parameter is not present, right?
Right now there is no separate stable documentation, only the one for the dev branch. I can see how that is confusing and should be fixed. I'll make sure the documentation is at least labeled correctly.

**Comment by capt-pyro** [comment]
Ohh, so just so i understand the pip version is stable (and doesn't have the portfolio parameter) while the dev branch has the portfolio option and has its documentation up on the site

**Comment by amueller** [comment]
Yes indeed, but that wasn't clear when you opened the issue, now the docs clarify they are 0.1.9-dev, they incorrectly said 0.1.8 before.

**Comment by amueller** [comment]
The stable version (0.18) also uses a portfolio but doesn't have a parameter to select which portfolio to use.

**Comment by amueller** [comment]
I'll close this in favor of #242, hope you don't mind.
