### ISSUE TITLE
need to adjust portfolios for AnyClassifier

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#243]
Right now the default portfolio is very small, and the "mixed" portfolio doesn't contain Random Forests or Logistic Regression.
@hp2500 do you have any cycles to work on this?

**Comment by hp2500** [comment]
@amueller yes, absolutely!

**Comment by amueller** [comment]
A quick fix would be to maybe append the mixed to the baseline one, even better would be of course to do a mixed with RandomForest and LogisticRegression ;)

**Comment by amueller** [comment]
fixed in #246
