### ISSUE TITLE
Missing Test Files

### ISSUE THREAD

**Issue by MertNuhuz** [dabl/dabl#30]
Most of the files defined in "testing" ipython notebook are not under the dataset folder. Maybe they can be removed?

`
avocado = pd.read_csv("/home/andy/datasets/avocado.csv", parse_dates=['Date'])
telco_churn = pd.read_csv("/home/andy/datasets/WA_Fn-UseC_-Telco-Customer-Churn.csv")
#restaurant = pd.read_csv("/home/andy/datasets/restaurant-and-market-health-violations.csv")
titanic = pd.read_csv("dabl/tests/titanic.csv")
ames = pd.read_excel("/home/andy/datasets/AmesHousing.xls")
cars = pd.read_excel("/home/andy/datasets/2018 FE Guide for DOE-release dates before 1-24-2018-no-sales-1-23-2018public.xlsx")
target = 'Comb Unadj FE - Conventional Fuel'
#accidents = pd.read_csv("/home/andy/datasets/Acc.csv")
#violations = pd.read_csv("/home/andy/datasets/Traffic_Violations.csv")
adult = pd.read_csv("/home/andy/datasets/adult.csv")
wine_quality = fetch_openml(data_id=287)`

**Comment by amueller** [comment]
Thanks for your comment. I should remove that notebook, it was not meant for public consumption, and I'll replace it with a clean tutorial.

**Comment by MertNuhuz** [comment]
Nice, I'm closing the subject, then.

**Comment by amueller** [comment]
I uploaded a small demo notebook, will expand it in the future.
