### ISSUE TITLE
fix detect_types on empty dataframe

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#301]
Right now calling ``detect_types`` on ``pd.DataFrame(columns=['something'])`` crashes. That should be fixed.

**Comment by parthpankajtiwary** [comment]
Hi @amueller,

I'd like to work on this issue. Quick question: I tried reproducing this issue but couldn't, command exists with a message stating `Empty DataFrame`. Perhaps the issue has already been fixed?

**Comment by amueller** [comment]
Hi @parthpankajtiwary. I don't think it has been fixed yet, can you post the code you ran and the traceback of the error?

**Comment by adityagandhamal** [comment]
Hello @amueller,

I have gone through the issue and seems like it has been resolved.
Following is the snippet supporting the above statement:

![Screenshot (869)](https://user-images.githubusercontent.com/61016383/150943898-16d3ce8e-da04-48ce-9ff7-fbacc8883a67.png)

**Comment by amueller** [comment]
Indeed, thanks for checking!
