### ISSUE TITLE
plot_supervised crashes with cleaned data

### ISSUE THREAD

**Issue by suvayu** [dabl/dabl#31]
I was trying to follow the examples in the [quick start guide](https://amueller.github.io/dabl/quick_start.html), but I see a crash when I call `plot_supervised` with a cleaned dataframe.  Passing the original dataframe works.  Here's an [example notebook](https://gist.github.com/suvayu/261b50ee95afab79c1ac47edf57cc8f2) with the titanic dataset.

PS: there are a few minor mistakes in the quick start guide, e.g. `detect_types_dataframe` should be `detect_types`, inconsistent namespace (sometimes you use `dabl.*`, sometimes the global namespace), etc.

**Comment by amueller** [comment]
Thanks for your feedback. Feel free to send a PR for the inconsistencies in the quick start guide.
Otherwise I'll try to fix them later today.
I'll get back to you on the notebook once I'm on my computer.

**Comment by amueller** [comment]
is the notebook still crashing on master?
I think some recent changes might have fixed this.

**Comment by amueller** [comment]
also doctests are working in master now so the guides should be running. I'm working on automatically pushing the current docs to the website right now.

**Comment by suvayu** [comment]
> is the notebook still crashing on master?
> I think some recent changes might have fixed this.

Indeed, the latest tip fixes the issue.

**Comment by amueller** [comment]
Thanks for checking!
