### ISSUE TITLE
URGENT: ImportError Issue with `detect_types` Module from `dabl` Library

### ISSUE THREAD

**Issue by GarYah822** [dabl/dabl#330]
Dear experts and fellow users,

I'm currently facing an issue with the `detect_types` module from the `dabl` library. Despite having ensured that both `dabl` and `sklearn` are up to date, I continue to encounter an ImportError.

Upon investigating, I discovered that the issue stems from the deprecation of the function 'if_delegate_has_method' in `sklearn.utils.metaestimators`, scheduled for removal in version 1.3.0 of scikit-learn.

I'm now seeking guidance on how to resolve this dilemma and successfully run the code. Any assistance or insights would be greatly appreciated!

Thank you in advance for your valuable assistance.
![WX20230902-194117@2x](https://github.com/dabl/dabl/assets/63391137/cb315b4c-3c2d-429e-89d8-efcc123e744b)

**Comment by bpkroth** [comment]
FWIW, current workaround is to `pip install "scikit-learn<1.3.0"`
