### ISSUE TITLE
maybe store adult in zipped format?

### ISSUE THREAD

**Issue by amueller** [dabl/dabl#36]
to make the repo smaller.

**Comment by suvayu** [comment]
Now that it's in the repo, it won't help.  In fact, it will make the repo bigger as now both the uncompressed and compressed versions will be stored.  To make the repo smaller, you will have to rewrite history, with all that comes with it, like all cloned repos out there will fail to `git pull` and will have to be "force synced" with the new `HEAD`.  Is that acceptable?

If so, the general steps are like this:
1. say the repo looks like this:

        ---A---B---C
    Where `A` is the commit where the csv file was introduced (fe1fb9a510), and `B` and `C` are unrelated commits made after `A`.

2. now compress the csv and add it to the repo, say in commit `D`.  Now the repo looks as below:

        ---A---B---C---D

3. now you will need to rebase and rearrange the commits to:

        ---A---D---B---C

    and squash `A` and `D`.

If things go well, the new history should look like this:

    ---A'---B'---C'

If you choose to go ahead, I can do the work.

**Comment by amueller** [comment]
Thanks for wanting to work on this.
I guess what I meant was not making the repo smaller but making the package smaller, which is relevant once it goes on pypi etc. You're right if someone checks out the full repo it won't help.

The problem with your proposal is that I need to force-push to master which might mess with people that checked out the current version, so I don't think I want to do that.

**Comment by suvayu** [comment]
Sorry, I misunderstood what you meant by repo.  Indeed the final PyPI package will be smaller.  In that case the fix is simpler.  I can try that as well :)  I guess all that needs changing is the `load_adult` function in `dabl/datasets/__init__.py`.

**Comment by amueller** [comment]
indeed, well and the stored file. I was being obtuse, sorry.
